<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Category extends Model {

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function ($category) {
            Cache::tags('categories')->flush();
            foreach ($category->posts as $post){
                Cache::forget('post-'.$post->id);
            }
        });
        static::deleted(function () {
            Cache::tags('categories')->flush();
        });
    }
    protected $dispatchesEvents =[
    ];

    protected $fillable = ['name'];

    public function getRouteKeyName()
    {
        return 'name';
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
    public function scopeWithPostsCount($query)
    {
        return $query->withCount('posts');
    }
    public function path()
    {
        return "/adwise_panel/categories/$this->name";
    }
}
